export const GET_GAME_SCHEDULE = "GET_GAME_SCHEDULE";
export type GET_GAME_SCHEDULE = typeof GET_GAME_SCHEDULE;

export const GAME_SCHEDULE_LOADED = "GAME_SCHEDULE_LOADED";
export type GAME_SCHEDULE_LOADED = typeof GAME_SCHEDULE_LOADED;

export const GET_GAME_RESPONSE = "GET_GAME_RESPONSE";
export type GET_GAME_RESPONSE = typeof GET_GAME_RESPONSE;

export const GAME_RESPONSE_LOADED = "GAME_RESPONSE_LOADED";
export type GAME_RESPONSE_LOADED = typeof GAME_RESPONSE_LOADED;